var BS = [
    {
        bsId: 1,
        isBsShow: false,
        isSpecialShow: false,
        bsName: '山西阳泉市大阳泉煤炭有限责任公司',
        publicDate: '2021年5月21日', 
        dropdownName: '阳泉市大阳泉煤炭有限公司', 
        download: '固废污染环境-防治信息公示大阳泉.xlsx',
        showDeadline: '2021-07-30',
    },
    {
        bsId: 2, 
        isBsShow: true,
        isSpecialShow: false,
        bsName: '汉中达鑫再生资源回收有限责任公司', 
        publicDate: '2021年6月23日', 
        dropdownName: '汉中达鑫再生资源回收公司', 
        download: '汉中达鑫再生资源回收有限责任公司公示.pdf',
        showDeadline: '2021-08-14'
    },
     {
        bsId: 3, 
        isBsShow: true,
        isSpecialShow: false,
        bsName: '府谷县田家寨镇新田煤矿有限公司', 
        publicDate: '2021年7月12日',
        dropdownName: '田家寨镇新田煤矿有限公司', 
        download: '府谷县田家寨镇新田煤矿有限公司.zip',
        showDeadline: '2021-12-31'
     },
     {
        bsId: 4,
        isBsShow: true,
        isSpecialShow: false,
        bsName: '陕西省榆林市府谷县府谷天化医院', 
        publicDate: '2021年7月12日', 
        dropdownName: '榆林市府谷县天化医院', 
        download: '榆林府谷天化医院.pdf',
        showDeadline: '2021-12-31',
     },
     {
      bsId: 5,
      isBsShow: true,
      isSpecialShow: false,
      bsName: '府谷县张明沟矿业有限责任公司', 
      publicDate: '2021年7月13日', 
      dropdownName: '张明沟矿业有限责任公司', 
      download: '张明沟煤矿固废公开信息.pdf',
      showDeadline: '2021-12-31',
    },
    {
      bsId: 6,
      isBsShow: true,
      isSpecialShow: false,
      bsName: '府谷县新民镇东沟联办煤矿', 
      publicDate: '2021年7月13日', 
      dropdownName: '府谷县新民镇东沟联办煤矿', 
      download: '府谷县新民镇东沟联办煤矿固废公示表.xls',
      showDeadline: '2021-12-31',
    },
    {
      bsId: 7,
      isBsShow: true,
      isSpecialShow: true,
      bsName: '府谷县东峰煤矿有限公司', 
      publicDate: '2021年7月14日', 
      dropdownName: '府谷县东峰煤矿有限公司', 
      download: '府谷县东峰煤矿有限公司2020年一般固体废物与危险废物信息公示.pdf',
      showDeadline: '2021-12-31',
    },
    {
      bsId: 8,
      isBsShow: true,
      isSpecialShow: true,
      bsName: '府谷县中联矿业有限公司', 
      publicDate: '2021年7月14日', 
      dropdownName: '府谷县中联矿业有限公司', 
      download: '中联煤矿固废公开信息.pdf',
      showDeadline: '2021-12-31',
    },
    {
      bsId: 9,
      isBsShow: true,
      isSpecialShow: true,
      bsName: '府谷县祥荣煤矿有限公司', 
      publicDate: '2021年7月19日', 
      dropdownName: '府谷县祥荣煤矿有限公司', 
      download: '府谷县祥荣煤矿有限公司.pdf',
      showDeadline: '2021-12-31',
    },
    {
      bsId: 10,
      isBsShow: true,
      isSpecialShow: true,
      bsName: '府谷县瑞泰煤矿有限公司', 
      publicDate: '2021年7月19日', 
      dropdownName: '府谷县瑞泰煤矿有限公司', 
      download: '瑞泰固废公开信息.pdf',
      showDeadline: '2021-12-31',
    },
    {
      bsId: 11,
      isBsShow: true,
      isSpecialShow: true,
      bsName: '府谷县工农联营煤矿', 
      publicDate: '2021年7月19日', 
      dropdownName: '府谷县工农联营煤矿', 
      download: '工农煤矿固废公开信息.pdf',
      showDeadline: '2021-12-31',
    },
    {
      bsId: 12,
      isBsShow: true,
      isSpecialShow: true,
      bsName: '府谷电力医院', 
      publicDate: '2021年7月19日', 
      dropdownName: '府谷电力医院', 
      download: '府谷电力医院.pdf',
      showDeadline: '2021-12-31',
    },
    {
      bsId: 13,
      isBsShow: true,
      isSpecialShow: true,
      bsName: '府谷县中医医院', 
      publicDate: '2021年7月20日', 
      dropdownName: '府谷县中医医院', 
      download: '府谷县中医医院.pdf',
      showDeadline: '2021-12-31',
    },
    {
      bsId: 14,
      isBsShow: true,
      isSpecialShow: false,
      bsName: '府谷县顺兴隆汽贸有限公司', 
      publicDate: '2021年7月21日', 
      dropdownName: '府谷县顺兴隆汽贸有限公司', 
      download: '府谷县顺兴隆汽贸有限公司.xlsx',
      showDeadline: '2021-12-31',
    }

]; 


